version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: . # Вказуємо контекст на кореневу директорію проекту
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./app:/app # Зв'язок з локальною директорією
    ports:
      - "8000:8000"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"

volumes:
  db-data: